# Конфігурація для файн-тюнінгу Qwen2.5-Coder
# Для гідропонного вирощування гороху

# Налаштування моделі
model:
  name: "Qwen/Qwen2.5-Coder-1.5B-Instruct"
  torch_dtype: "float16"
  device_map: "auto"
  load_in_4bit: true
  load_in_8bit: false

# Налаштування LoRA
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj" 
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

# Налаштування даних
data:
  train_file: "/workspace/data/processed/train_dataset.jsonl"
  eval_file: "/workspace/data/processed/eval_dataset.jsonl"
  max_length: 512
  instruction_template: "Instruction: {instruction}\nInput: {input}\nOutput: {output}"

# Параметри тренування
training:
  output_dir: "/workspace/models/finetuned"
  num_train_epochs: 3
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_steps: 100
  logging_steps: 10
  save_steps: 100
  eval_steps: 50
  evaluation_strategy: "steps"
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  dataloader_num_workers: 0
  remove_unused_columns: false
  optim: "adamw_torch"
  fp16: true
  gradient_checkpointing: true
  report_to: "tensorboard"

# Налаштування логування
logging:
  tensorboard_dir: "/workspace/logs/tensorboard"
  log_level: "INFO"

# Налаshtування раннього зупинення
early_stopping:
  enabled: true
  patience: 3
  threshold: 0.001
